blueprint:
  name: Ventilation control
  description: Control ventilation based on time and settings
  domain: automation
  input:
    day_vent_time:
      name: Day Vent Time
      description: Time to start day ventilation
      default: "08:00"
      selector:
        time: {}
    night_vent_time:
      name: Night Vent Time
      description: Time to start night ventilation
      default: "20:30"
      selector:
        time: {}
    max_vent_time:
      name: Max Vent Time
      description: Time to start max ventilation
      default: "21:30"
      selector:
        time: {}
    day_vent:
      name: Day Vent
      description: Ventilation level during the day
      default: 50
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    night_vent:
      name: Night Vent
      description: Ventilation level during the night
      default: 30
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    max_vent:
      name: Max Vent
      description: Ventilation level during max ventilation
      default: 100
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
    max_vent_enabled:
      name: Max vent enabled
      description: Enable mx vent time
      default: true
      selector:
        boolean: {}
    holiday_mode_enabled:
      name: Holiday mode
      description: Enable holiday mode
      default: false
      selector:
        boolean: {}

variables:
  v_day_vent: !input 'day_vent'
  v_night_vent: !input 'night_vent'
  v_max_vent: !input 'max_vent'
  v_max_enabled: !input 'max_vent_enabled'
  v_holiday_enabled: !input 'holiday_mode_enabled'

trigger:
  - platform: time
    at: !input 'day_vent_time'
    id: 'day'
  - platform: time
    at: !input 'night_vent_time'
    id: 'night'
  - platform: time
    at: !input 'max_vent_time'
    id: 'max'

action:
  - variables:
      vent_value: >
        {% if trigger.id == 'max' and v_holiday_enabled == false and v_max_enabled == true %}
          {{ v_max_vent }}
        {% elif trigger.id == 'day' and v_holiday_enabled == false %}
          {{ v_day_vent }}
        {% else %}
          {{ v_night_vent }}
        {% endif %}
  - service: modbus.write_register
    data:
      address: 4210
      unit: 10
      value: "{{ vent_value }}"
      hub: RS485
  - service: input_number.set_value
    target:
      entity_id: input_number.slider2
    data:
      value: "{{ vent_value }}"

mode: single
