blueprint:
  name: Airpack Home daily schedul
  description: 'Set times for different vent %'
  domain: automation
  input:
    start_max_vent_time:
      name: Start Max Vent Time
      default: "20:30:00"
      has_date: false
    start_day_vent_time:
      name: Start Day Vent Time
      default: "08:00:00"
      has_date: false
    start_night_vent_time:
      name: Start Night Vent Time
      default: "21:30:00"
      has_date: false 

trigger:
  - platform: time
    at: !input 'start_max_vent_time'
  - platform: time
    at: !input 'start_day_vent_time'
  - platform: time
    at: !input 'start_night_vent_time'

action:
  - variables:
      vent_value: >
        {% if trigger.now.time() == states(start_max_vent_time) %}
          100
        {% elif trigger.now.time() == states(start_day_vent_time) %}
          50
        {% elif trigger.now.time() == states(start_night_vent_time) %}
          30
        {% endif %}
  - service: modbus.write_register
    data:
      address: 4210
      unit: 10
      value: "{{ vent_value }}"
      hub: RS485
  - service: input_number.set_value
    target:
      entity_id: input_number.slider2
    data:
      value: "{{ vent_value }}"

mode: single
