blueprint:
  domain: automation
  name: Window and Roof Cover Automation
  description: |
    This automation opens the window cover at specified times on weekdays and weekends and
    also opens the roof cover when the temperature is above the threshold v.240122_1337
  source_url: 'https://github.com/wsiczek/ha/blob/main/cover_open.yaml'
  input:
    window_cover:
      name: Window Cover
      description: "Window cover entity"
      selector:
        entity:
          domain: cover
    roof_cover:
      name: Roof Cover
      description: "Roof cover entity"
      selector:
        entity:
          domain: cover
    time_weekday:
      name: Time Weekday
      description: "Time weekday"
      default: '07:00:00'
      selector:
        time:
    time_weekend:
      name: Time Weekend
      description: "Time weekend"
      default: '08:00:00'
      selector:
        time:
        
variables:
  v_holiday: "{{ states('input_boolean.holiday_mode') }}"
  v_workday: "{{ states('binary_sensor.workday_sensor') }}"
  v_outside_temp: "{{ states('sensor.airpack_zewn') }}"
  v_thres_temp: "{{ states('input_number.threshold_temperature') }}"
  
trigger:
  - platform: time
    at: !input 'time_weekday'
    id: 'weekday'
  - platform: time
    at: !input 'time_weekend'
    id: 'weekend'

condition:
  - condition: template
    value_template: >
      {% if v_holiday == 'off' and v_workday == 'on' and trigger.id == 'weekday' %}
        true
      {% elif v_holiday == 'off' and v_workday == 'off' and trigger.id == 'weekend' %}
        true
      {% else %}
        false
      {% endif %}

action:
  - service: cover.open_cover
    target:
      entity_id: !input window_cover
  - choose:
    - conditions:
      - condition: template
        value_template: >
          {% if v_outside_temp >= v_thres_temp %}
            true
          {% else %}
            false
          {% endif %}
      sequence:
      - service: cover.open_cover
        target:
          entity_id: !input roof_cover

mode: single
