blueprint:
  domain: automation
  name: Window and Roof Cover Automation
  description: |
    This automation opens the window cover at specified times on weekdays and weekends and
    also opens the roof cover when the temperature is above the threshold.
  input:
    workday_sensor:
      name: Workday Sensor
      description: "Sensor indicating if it's a workday"
      selector:
        entity:
          domain: binary_sensor
    window_cover:
      name: Window Cover
      description: "Window cover entity"
      selector:
        entity:
          domain: cover
    roof_cover:
      name: Roof Cover
      description: "Roof cover entity"
      selector:
        entity:
          domain: cover
    outside_temperature_sensor:
      name: Outside Temperature Sensor
      description: "Temperature sensor for outside temperature"
      selector:
        entity:
          domain: sensor
    time_weekday:
      name: Time Weekday
      description: "Time weekday"
      default: '07:00:00'
      selector:
        time:
    time_weekend:
      name: Time Weekend
      description: "Time weekend"
      default: '08:00:00'
      selector:
        time:
    threshold_temperature:
      name: Threshold Temperature
      description: "Threshold temperature"
      default: 5
      selector:
        number:
         min: -10
         max: 10
         unit_of_measurement: "°C"
  source_url: 'https://github.com/wsiczek/ha/'
  
mode: restart
max_exceeded: silent

trigger:
  - platform: time
    at: !input time_weekday
  - platform: time
    at: !input time_weekend

condition:
  - condition: template
    value_template: >
      {% if is_state('!input workday_sensor', 'on') and now().hour == states('!input time_weekday').hour %}
        true
      {% elif is_state('!input workday_sensor', 'off') and now().hour == states('!input time_weekend').hour %}
        true
      {% else %}
        false
      {% endif %}

action:
  - service: cover.open_cover
    target:
      entity_id: !input window_cover
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: !input outside_temperature_sensor
        above: !input threshold_temperature
      sequence:
      - service: cover.open_cover
        target:
          entity_id: !input roof_cover


