blueprint:
  name: Turn Switch On/Off at Defined Time
  description: Turn a switch on or off at specified times
  domain: automation
  input:
    switch_entity:
      name: Switch
      selector:
        entity:
          domain: switch
    time_entity:
      name: Time
      selector:
        time:
    type:
      name: Type
      selector:
        dropdown:
          options:
            - ON
            - OFF

trigger:
  platform: time
  at: !input time_entity

action:
  - service_template: "switch.turn_{{ type }}"
    target:
      entity_id: !input switch_entity
