blueprint:
  name: On-Off Schedule for Switch Entity
  description: Turn ON and OFF a switch entity based on specified times.
  domain: automation
  input:
    automation_target:
      name: Automation target
      description: The target switch entity to control.
      selector:
        entity:
          domain: switch
    time_blocks:
      name: Time Blocks
      description: Configure the ON and OFF time blocks.
      selector:
        time:
          multiple: true
  trigger:
    - platform: time
      at: !input time_blocks
  action:
    - service_template: >
        switch.turn_{{ 'on' if now().time() >= strptime(on_time, '%H:%M:%S').time() else 'off' }}
      entity_id: !input automation_target
