blueprint:
  name: ZigBee Remote Automation
  description: Create an automation for a ZigBee remote with 4 buttons and 3 press types v.241122_1405
  domain: automation
  source_url: 'https://github.com/wsiczek/ha/blob/main/zigbee_remote.yaml'
  input:
    remote:
      name: ZigBee Remote
      description: The ZigBee remote to use
      selector:
        device:
          integration: zha
    button_1_short:
      name: Button 1 Short Press
      description: The action to perform when button 1 is pressed shortly
      default: []
      selector:
        action: {}
    button_1_long:
      name: Button 1 Long Press
      description: The action to perform when button 1 is pressed long
      default: []
      selector:
        action: {}
    button_1_double:
      name: Button 1 Double Press
      description: The action to perform when button 1 is pressed twice
      default: []
      selector:
        action: {}

    button_2_short:
      name: Button 2 Short Press
      description: The action to perform when button 1 is pressed shortly
      default: []
      selector:
        action: {}
    button_2_long:
      name: Button 2 Long Press
      description: The action to perform when button 1 is pressed long
      default: []
      selector:
        action: {}
    button_2_double:
      name: Button 2 Double Press
      description: The action to perform when button 1 is pressed twice
      default: []
      selector:
        action: {}

    button_3_short:
      name: Button 3 Short Press
      description: The action to perform when button 1 is pressed shortly
      default: []
      selector:
        action: {}
    button_3_long:
      name: Button 3 Long Press
      description: The action to perform when button 1 is pressed long
      default: []
      selector:
        action: {}
    button_3_double:
      name: Button 3 Double Press
      description: The action to perform when button 1 is pressed twice
      default: []
      selector:
        action: {}

    button_4_short:
      name: Button 4 Short Press
      description: The action to perform when button 1 is pressed shortly
      default: []
      selector:
        action: {}
    button_4_long:
      name: Button 4 Long Press
      description: The action to perform when button 1 is pressed long
      default: []
      selector:
        action: {}
    button_4_double:
      name: Button 4 Double Press
      description: The action to perform when button 1 is pressed twice
      default: []
      selector:
        action: {}
        
mode: single
max_exceeded: silent
variables:
  device_id: !input 'remote'
trigger:
  - platform: event
    event_type: zha_event
condition: "{{ trigger.event.data.device_id == device_id }}"
action:
  - variables:
      button: "{{ trigger.event.data.command }}"
      press_type: "{{ trigger.event.data.args.press_type }}"
      my_var: "{{ trigger.event.data.endpoint_id }}"
  - choose:
    - conditions: "{{ button == 'button_1' and press_type == 'press' }}"
      sequence: !input 'button_1_short'
    - conditions: "{{ button == 'button_1' and press_type == 'hold' }}"
      sequence: !input 'button_1_long'
    - conditions: "{{ button == 'button_1' and press_type == 'double' }}"
      sequence: !input 'button_1_double'

    - conditions: "{{ button == 'button_2' and press_type == 'press' }}"
      sequence: !input 'button_2_short'
    - conditions: "{{ button == 'button_2' and press_type == 'hold' }}"
      sequence: !input 'button_2_long'
    - conditions: "{{ button == 'button_2' and press_type == 'double' }}"
      sequence: !input 'button_2_double'

    - conditions: "{{ button == 'button_3' and press_type == 'press' }}"
      sequence: !input 'button_3_short'
    - conditions: "{{ button == 'button_3' and press_type == 'hold' }}"
      sequence: !input 'button_3_long'
    - conditions: "{{ button == 'button_3' and press_type == 'double' }}"
      sequence: !input 'button_3_double'

    - conditions: "{{ button == 'button_4' and press_type == 'press' }}"
      sequence: !input 'button_4_short'
    - conditions: "{{ button == 'button_4' and press_type == 'hold' }}"
      sequence: !input 'button_4_long'
    - conditions: "{{ button == 'button_4' and press_type == 'double' }}"
      sequence: !input 'button_4_double'
